-- INSERT INTO team (name, alias, stadium)
-- VALUES
-- ("AFC Bournemouth", "Bournemouth", "Dean Court"),
-- ("Arsenal", "Arsenal", "Emirates Stadium"),
-- ("Brighton & Hove Albion", "Brighton", "Falmer Stadium"),
-- ("Burnley", "Burnley", "Turf Moor"),
-- ("Chelsea", "Chelsea", "Stamford Bridge"),
-- ("Crystal Palace", "Crystal Palace", "Selhurst Park"),
-- ("Everton", "Everton", "Goodison Park"),
-- ("Huddersfield Town", "Huddersfield", "John Smith's Stadium"),
-- ("Leicester City", "Leicester",  "King Power Stadium"),
-- ("Liverpool", "Liverpool", "Anfield"),
-- ("Manchester City", "Man City", "Etihad Stadium"),
-- ("Manchester United", "Man United", "Old Trafford"),
-- ("Newcastle United", "Newcastle", "St James' Park"),
-- ("Southampton", "Southampton", "St Mary's Stadium"),
-- ("Stoke City", "Stoke", "bet365 Stadium"),
-- ("Swansea City", "Swansea", "Liberty Stadium"),
-- ("Tottenham Hotspur", "Tottenham", "Wembley Stadium"),
-- ("Watford", "Watford", "Vicarage Road"),
-- ("West Bromwich Albion", "West Brom", "The Hawthorns"),
-- ("West Ham United", "West Ham", "London Stadium"),
-- ("Aston Villa", "Aston Villa", "Villa Park"),
-- ("Barnsley", "Barnsley", "Oakwell"),
-- ("Birmingham City", "Birmingham", "St Andrew's"),
-- ("Bolton Wanderers", "Bolton", "Macron Stadium"),
-- ("Brentford", "Brentford", "Griffin Park"),
-- ("Bristol City", "Bristol City", "Ashton Gate"),
-- ("Burton Albion", "Burton", "Pirelli Stadium"),
-- ("Cardiff City", "Cardiff", "Cardiff City Stadium"),
-- ("Derby County", "Derby", "Pride Park Stadium"),
-- ("Fulham", "Fulham", "Craven Cottage"),
-- ("Hull City", "Hull", "KCOM Stadium"),
-- ("Ipswich Town", "Ipswich", "Portman Road"),
-- ("Leeds United", "Leeds", "Elland Road"),
-- ("Middlesbrough", "Middlesbrough", "Riverside Stadium"),
-- ("Millwall", "Millwall", "The Den"),
-- ("Norwich City", "Norwich", "Carrow Road"),
-- ("Nottingham Forest", "Nott'm Forest", "City Ground"),
-- ("Preston North End", "Preston", "Deepdale"),
-- ("Queens Park Rangers", "QPR", "Loftus Road"),
-- ("Reading", "Reading", "Madejski Stadium"),
-- ("Sheffield United", "Sheffield United", "Bramall Lane"),
-- ("Sheffield Wednesday", "Sheffield Weds", "Hillsborough Stadium"),
-- ("Sunderland", "Sunderland", "Stadium of Light"),
-- ("Wolverhampton Wanderers", "Wolves", "Molineux"),
-- ("AFC Wimbledon", "AFC Wimbledon", "Kingsmeadow"),
-- ("Blackburn Rovers", "Blackburn", "Ewood Park"),
-- ("Blackpool", "Blackpool", "Bloomfield Road"),
-- ("Bradford City", "Bradford", "Valley Parade"),
-- ("Bristol Rovers", "Bristol Rvs", "Memorial Stadium"),
-- ("Bury", "Bury", "Gigg Lane"),
-- ("Charlton Athletic", "Charlton", "The Valley"),
-- ("Doncaster Rovers", "Doncaster", "Keepmoat Stadium"),
-- ("Fleetwood Town", "Fleetwood Town", "Highbury Stadium"),
-- ("Gillingham", "Gillingham", "Priestfield Stadium"),
-- ("Milton Keynes Dons", "Milton Keynes Dons", "Stadium:mk"),
-- ("Northampton Town", "Northampton", "Sixfields Stadium"),
-- ("Oldham Athletic", "Oldham", "Boundary Park"),
-- ("Oxford United", "Oxford", "Kassam Stadium"),
-- ("Peterborough United", "Peterboro", "London Road"),
-- ("Plymouth Argyle", "Plymouth", "Home Park"),
-- ("Portsmouth", "Portsmouth", "Fratton Park"),
-- ("Rochdale", "Rochdale", "Spotland Stadium"),
-- ("Rotherham United", "Rotherham", "New York Stadium"),
-- ("Scunthorpe United", "Scunthorpe", "Glanford Park"),
-- ("Shrewsbury Town", "Shrewsbury", "New Meadow"),
-- ("Southend United", "Southend", "Roots Hall"),
-- ("Walsall", "Walsall", "Bescot Stadium"),
-- ("Wigan Athletic", "Wigan", "DW Stadium"),
-- ("Accrington Stanley", "Accrington", "Crown Ground"),
-- ("Barnet", "Barnet", "The Hive Stadium"),
-- ("Cambridge United", "Cambridge", "Abbey Stadium"),
-- ("Carlisle United", "Carlisle", "Brunton Park"),
-- ("Cheltenham Town", "Cheltenham", "Whaddon Road"),
-- ("Chesterfield", "Chesterfield", "Proact Stadium"),
-- ("Colchester United", "Colchester", "Colchester Community Stadium"),
-- ("Coventry City", "Coventry", "Ricoh Arena"),
-- ("Crawley Town", "Crawley Town", "Broadfield Stadium"),
-- ("Crewe Alexandra", "Crewe", "Gresty Road"),
-- ("Exeter City", "Exeter", "St James Park"),
-- ("Forest Green Rovers", "Forest Green", "The New Lawn"),
-- ("Grimsby Town", "Grimsby", "Blundell Park"),
-- ("Lincoln City", "Lincoln", "Sincil Bank"),
-- ("Luton Town", "Luton", "Kenilworth Road"),
-- ("Mansfield Town", "Mansfield", "Field Mill"),
-- ("Morecambe", "Morecambe", "Globe Arena"),
-- ("Newport County", "Newport County", "Rodney Parade"),
-- ("Notts County", "Notts County", "Meadow Lane"),
-- ("Port Vale", "Port Vale", "Vale Park"),
-- ("Stevenage", "Stevenage", "Broadhall Way"),
-- ("Swindon Town", "Swindon", "County Ground"),
-- ("Wycombe Wanderers", "Wycombe", "Adams Park"),
-- ("Yeovil Town", "Yeovil", "Huish Park"),
-- ("Amiens", "Amiens", "Stade de la Licorne"),
-- ("Angers", "Angers", "Stade Raymond Kopa"),
-- ("Bordeaux", "Bordeaux", "Matmut Atlantique"),
-- ("Caen", "Caen", "Stade Michel d'Ornano"),
-- ("Dijon", "Dijon", "Stade Gaston Gérard"),
-- ("Guingamp", "Guingamp", "Stade du Roudourou"),
-- ("Lille", "Lille", "Stade Pierre-Mauroy"),
-- ("Lyon", "Lyon", "Parc OL"),
-- ("Marseille", "Marseille", "Stade Vélodrome"),
-- ("Metz", "Metz", "Stade Saint-Symphorien"),
-- ("Monaco", "Monaco", "Stade Louis II"),
-- ("Montpellier", "Montpellier", "Stade de la Mosson"),
-- ("Nantes", "Nantes", "Stade de la Beaujoire"),
-- ("Nice", "Nice", "Allianz Riviera"),
-- ("Paris Saint-Germain", "Paris SG", "Parc des Princes"),
-- ("Rennes", "Rennes", "Roazhon Park"),
-- ("Saint-Étienne", "St Etienne", "Stade Geoffroy-Guichard"),
-- ("Strasbourg", "Strasbourg", "Stade de la Meinau"),
-- ("Toulouse", "Toulouse", "Stadium Municipal"),
-- ("Troyes", "Troyes", "Stade de l'Aube"),
-- ("FC Augsburg", "Augsburg", "WWK Arena"),
-- ("Hertha BSC", "Hertha", "Olympiastadion"),
-- ("Werder Bremen", "Werder Bremen", "Weser-Stadion"),
-- ("Borussia Dortmund", "Dortmund", "Signal Iduna Park"),
-- ("Eintracht Frankfurt", "Ein Frankfurt", "Commerzbank-Arena"),
-- ("SC Freiburg", "Freiburg", "Schwarzwald-Stadion"),
-- ("Hamburger SV", "Hamburg", "Volksparkstadion"),
-- ("Hannover 96", "Hannover", "HDI-Arena"),
-- ("1899 Hoffenheim", "Hoffenheim", "Wirsol Rhein-Neckar-Arena"),
-- ("1. FC Köln", "FC Koln", "RheinEnergieStadion"),
-- ("RB Leipzig", "RB Leipzig", "Red Bull Arena"),
-- ("Bayer Leverkusen", "Leverkusen", "BayArena"),
-- ("Mainz 05", "Mainz", "Opel Arena"),
-- ("Borussia Mönchengladbach", "M'gladbach", "Borussia-Park"),
-- ("Bayern Munich", "Bayern Munich", "Allianz Arena"),
-- ("Schalke 04", "Schalke 04", "Veltins-Arena"),
-- ("VfB Stuttgart", "Stuttgart", "Mercedes-Benz Arena"),
-- ("VfL Wolfsburg", "Wolfsburg", "Volkswagen Arena"),
-- ("Atalanta", "Atalanta", "Stadio Atleti Azzurri d'Italia"),
-- ("Benevento", "Benevento", "Stadio Ciro Vigorito"),
-- ("Bologna", "Bologna", "Stadio Renato Dall'Ara"),
-- ("Cagliari", "Cagliari", "Sardegna Arena"),
-- ("Chievo", "Chievo", "Stadio Marc'Antonio Bentegodi"),
-- ("Crotone", "Crotone", "Stadio Ezio Scida"),
-- ("Fiorentina", "Fiorentina", "Stadio Artemio Franchi"),
-- ("Genoa", "Genoa", "Stadio Luigi Ferraris"),
-- ("Hellas Verona", "Verona", "Stadio Marc'Antonio Bentegodi"),
-- ("Internazionale", "Inter", "San Siro"),
-- ("Juventus", "Juventus", "Allianz Stadium"),
-- ("Lazio", "Lazio", "Stadio Olimpico"),
-- ("Milan", "Milan", "San Siro"),
-- ("Napoli", "Napoli", "Stadio San Paolo"),
-- ("Roma", "Roma", "Stadio Olimpico"),
-- ("Sampdoria", "Sampdoria", "Stadio Luigi Ferraris"),
-- ("Sassuolo", "Sassuolo", "Mapei Stadium – Città del Tricolore "),
-- ("SPAL", "Spal", "Paolo Mazza"),
-- ("Torino", "Torino", "Stadio Olimpico Grande Torino"),
-- ("Udinese", "Udinese", "Stadio Friuli-Dacia Arena"),
-- ( "Alavés", "Alaves", "Mendizorrotza"),
-- ( "Athletic Bilbao", "Ath Bilbao", "San Mamés"),
-- ( "Atlético Madrid", "Ath Madrid", "Vicente Calderón"),
-- ( "Barcelona", "Barcelona", "Camp Nou"),
-- ( "Celta Vigo", "Celta", "Balaídos"),
-- ( "Deportivo La Coruña", "La Coruna", "Riazor"),
-- ( "Eibar", "Eibar", "Ipurua"),
-- ( "Espanyol", "Espanol", "RCDE Stadium"),
-- ( "Getafe", "Getafe", "Coliseum Alfonso Pérez"),
-- ( "Girona", "Girona", "Montilivi"),
-- ( "Las Palmas", "Las Palmas", "Gran Canaria"),
-- ( "Leganés", "Leganes", "Butarque"),
-- ( "Levante", "Levante", "Ciutat de València"),
-- ( "Málaga", "Malaga", "La Rosaleda"),
-- ( "Real Betis", "Betis", "Benito Villamarín"),
-- ( "Real Madrid", "Real Madrid", "Santiago Bernabéu"),
-- ( "Real Sociedad", "Sociedad", "Anoeta"),
-- ( "Sevilla", "Sevilla", "Ramón Sánchez Pizjuán"),
-- ( "Valencia", "Valencia", "Mestalla"),
-- ( "Villarreal", "Villarreal", "Estadio de la Cerámica"),
-- ("ADO Den Haag", "Den Haag", "Cars Jeans Stadion"),
-- ("Ajax", "Ajax", "Amsterdam ArenA"),
-- ("AZ", "AZ Alkmaar", "AFAS Stadion"),
-- ("Excelsior", "Excelsior", "Van Donge & De Roo Stadion"),
-- ("Feyenoord", "Feyenoord", "Stadion Feijenoord"),
-- ("FC Groningen", "Groningen", "Noordlease Stadion"),
-- ("sc Heerenveen", "Heerenveen", "Abe Lenstra Stadion"),
-- ("Heracles Almelo", "Heracles", "Polman Stadion"),
-- ("NAC Breda", "NAC Breda", "Rat Verlegh Stadion"),
-- ("PEC Zwolle", "Zwolle", "MAC³PARK stadion"),
-- ("PSV", "PSV Eindhoven", "Philips Stadion"),
-- ("Roda JC Kerkrade", "Roda", "Parkstad Limburg Stadion"),
-- ("Sparta Rotterdam", "Sparta Rotterdam", "Het Kasteel"),
-- ("FC Twente", "Twente", "De Grolsch Veste"),
-- ("FC Utrecht", "Utrecht", "Stadion Galgenwaard"),
-- ("Vitesse", "Vitesse", "GelreDome"),
-- ("VVV-Venlo", "VVV Venlo", "Seacon Stadion - De Koel -"),
-- ("Willem II", "Willem II", "Koning Willem II-stadion"),
-- ("Anderlecht", "Anderlecht", "Constant Vanden Stock Stadium"),
-- ("Antwerp", "Antwerp", "Bosuilstadion"),
-- ("Charleroi", "Charleroi", "Stade du Pays de Charleroi"),
-- ("Club", "Club Brugge", "Jan Breydel Stadium"),
-- ("Eupen", "Eupen", "Kehrweg Stadion"),
-- ("Genk", "Genk", "Luminus Arena"),
-- ("Gent", "Gent", "Ghelamco Arena"),
-- ("Kortrijk", "Kortrijk", "Guldensporen Stadion"),
-- ("Lokeren", "Lokeren", "Daknamstadion"),
-- ("Mechelen", "Mechelen", "AFAS-stadion Achter de Kazerne"),
-- ("Mouscron", "Mouscron", "Stade Le Canonnier"),
-- ("Oostende", "Oostende", "Versluys Arena"),
-- ("Sint-Truiden", "St Truiden", "Stayen"),
-- ("Standard", "Standard", "Stade Maurice Dufrasne"),
-- ("Waasland", "Waasland-Beveren", "Freethiel Stadion"),
-- ("Zulte", "Waregem", "Regenboogstadion"),
-- ("Belenenses", "Belenenses", "Estádio do Restelo"),
-- ("Benfica", "Benfica", "Estádio da Luz"),
-- ("Boavista", "Boavista", "Estádio do Bessa"),
-- ("Braga", "Sp Braga", "Estádio Municipal de Braga"),
-- ("Chaves", "Chaves", "Estádio Municipal Eng. Manuel Branco Teixeira"),
-- ("Desportivo das Aves", "Aves", "Estádio do CD Aves"),
-- ("Estoril", "Estoril", "Estádio António Coimbra da Mota"),
-- ("Feirense", "Feirense", "Estádio Marcolino de Castro"),
-- ("Marítimo", "Maritimo", "Estádio do Marítimo"),
-- ("Moreirense", "Moreirense", "Parque de Jogos Comendador Joaquim de Almeida Freitas"),
-- ("Paços de Ferreira", "Pacos Ferreira", "Estádio Capital do Móvel"),
-- ("Porto", "Porto", "Estádio do Dragão"),
-- ("Portimonense", "Portimonense", "Estádio Municipal de Portimão"),
-- ("Rio Ave", "Rio Ave", "Estádio dos Arcos"),
-- ("Sporting CP", "Sp Lisbon", "Estádio José Alvalade"),
-- ("Tondela", "Tondela", "Estádio João Cardoso"),
-- ("Vitória de Guimarães", "Guimaraes", "Estádio D. Afonso Henriques"),
-- ("Vitória de Setúbal", "Setubal", "Estádio do Bonfim"),
-- ("Akhisar Belediyespor", "Akhisar Belediyespor", "Manisa 19 Mayıs Stadium"),
-- ("Alanyaspor", "Alanyaspor", "Alanya Oba Stadium"),
-- ("Antalyaspor", "Antalyaspor", "Antalya Stadium"),
-- ("Beşiktaş", "Besiktas", "Vodafone Park"),
-- ("Bursaspor", "Bursaspor", "Timsah Arena"),
-- ("Fenerbahçe", "Fenerbahce", "Ülker Stadium"),
-- ("Galatasaray", "Galatasaray", "Türk Telekom Stadium"),
-- ("Gençlerbirliği", "Genclerbirligi", "Ankara 19 Mayıs Stadium"),
-- ("Göztepe", "Goztep", "Bornova Stadium"),
-- ("İstanbul Başakşehir", "Buyuksehyr", "Başakşehir Fatih Terim Stadium"),
-- ("Kardemir Karabükspor", "Karabukspor", "Dr. Necmettin Şeyhoğlu Stadium"),
-- ("Kasımpaşa", "Kasimpasa", "Recep Tayyip Erdoğan Stadium"),
-- ("Kayserispor", "Kayserispor", "Kadir Has Stadium"),
-- ("Konyaspor", "Konyaspor", "Konya Büyükşehir Stadium"),
-- ("Osmanlıspor", "Osmanlispor", "Osmanlı Stadyumu"),
-- ("Sivasspor", "Sivasspor", "Sivas Arena"),
-- ("Trabzonspor", "Trabzonspor", "Şenol Güneş Stadium"),
-- ("Yeni Malatyaspor", "Yeni Malatyaspor", "Malatya İnönü Stadium"),
-- ("Aberdeen", "Aberdeen", "Pittodrie Stadium"),
-- ("Celtic", "Celtic", "Celtic Park"),
-- ("Dundee", "Dundee", "Dens Park"),
-- ("Hamilton Academical", "Hamilton", "New Douglas Park"),
-- ("Heart of Midlothian", "Hearts", "Tynecastle Stadium"),
-- ("Hibernian", "Hibernian", "Easter Road"),
-- ("Kilmarnock", "Kilmarnock", "Rugby Park"),
-- ("Motherwell", "Motherwell", "Fir Park"),
-- ("Partick Thistle", "Partick", "Firhill Stadium"),
-- ("Rangers", "Rangers", "Ibrox Stadium"),
-- ("Ross County", "Ross County", "Victoria Park"),
-- ("St Johnstone", "St Johnstone", "McDiarmid Park");

INSERT INTO public.league (name)
VALUES ('Israeli Premier League'),
       ('English Premier League'),
       ('English Championship'),
       ('English League One'),
       ('English League Two'),
       ('France Ligue 1'),
       ('German Bundesliga'),
       ('Italy Serie A'),
       ('Spanish La Liga'),
       ('Holland Eredivisie'),
       ('Belgium First Division A'),
       ('Portugal Primeira Liga'),
       ('Turkish Süper Lig'),
       ('Scotland Premiership');


INSERT INTO public.season (year, seasonstart, seasonend)
VALUES ('2008', '2007-08-11', '2008-05-13'),
       ('2009', '2008-08-04', '2009-05-06'),
       ('2010', '2009-08-05', '2010-05-05'),
       ('2011', '2010-08-05', '2011-05-05'),
       ('2012', '2011-08-04', '2012-05-19'),
       ('2013', '2012-08-18', '2013-05-12'),
       ('2014', '2013-08-19', '2014-05-20'),
       ('2015', '2014-08-18', '2015-05-20'),
       ('2016', '2015-08-11', '2016-05-06'),
       ('2017', '2016-07-28', '2017-06-30'),
       ('2018', '2017-08-06', '2018-05-12'),
       ('2019', '2018-08-11', '2019-05-20'),
       ('2020', '2019-08-05', '2020-04-07');